language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zanelib1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zanelib1/docker-react npm run test
